spring:
  application:
    name: lavanda-filebot-parser
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: bitnami
    listener:
        simple:
            retry:
                enabled: true
                initial-interval: 3s
                max-attempts: 1
                max-interval: 10s
                multiplier: 2  
cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-1
    sns:
      enabled: true    
server.port: 0      