server:
  port: 8080
spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 20s
          max-attempts: 3
          max-interval: 40s
          multiplier: 2
