spring:
    data: 
        mongodb:
            authentication-database: admin
            database: lavanda 
            host: localhost 
            password:  example
            port: 27017 
            username: root    
telegram:
  filebotbot:
    token: 5025549707:AAGfWqnBULjz1F67Jx8KvvF6hKdsIgfd-SU
    username: testingbot         
    authorized: 
      usernames: 
        - luisca_jl
        - CarlUndert
        - Vatalx
        - chemg